CREATE TABLE pet_user (ID INT(5) NOT NULL AUTO_INCREMENT,USER_NAME VARCHAR(25) NOT NULL UNIQUE,USER_PASSWD VARCHAR(25) NOT NULL,PRIMARY KEY (ID));
CREATE TABLE PETS ( PET_ID INT(5) NOT NULL AUTO_INCREMENT,PET_NAME VARCHAR(55) NOT NULL,PET_AGE INT(2),PET_PLACE VARCHAR(55),OWNER_ID INT(5),FOREIGN KEY (OWNER_ID)
REFERENCES PET_USER(ID) ON DELETE CASCADE, PRIMARY KEY (PET_ID));
DESC pets;
INSERT INTO PETS VALUES(1,'Jicko',4,'CH', NULL);
INSERT INTO PETS VALUES(2,'Lola',2,'DL', NULL);
INSERT INTO PETS VALUES(3,'Chacko',3,'BL', NULL);
INSERT INTO PETS VALUES(4,'Tommy',3,'BL', 1);